eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: op-sys-mall-api
  profiles:
    active: dev
logging:
  config: classpath:logback-${spring.profiles.active}.xml