eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.104:8761/eureka/
spring:
  application:
    name: service-feign
  profiles:
    active: prod
logging:
  config: classpath:logback-${spring.profiles.active}.xml