eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: op-sys-mall-ribbon
  profiles:
    active: dev
logging:
  config: classpath:logback-${spring.profiles.active}.xml