eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.104:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: service-hi
  profiles:
    active: dev
logging:
  config: classpath:logback-${spring.profiles.active}.xml