eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/
server:
 port: 8769
spring:
 application:
  name: op-sys-gateway-zuul-server
zuul:
 routes:
  op-sys-mall-api: /mall-api/**
  op-sys-mall-ribbon: /mall-ribbon/**
